name: Cypress Tests Lint & Format Check

on:
  pull_request:
    paths:
      - 'ConcernsCaseWork/ConcernsCaseWork.CypressTests/**'

jobs:
  lint-and-format:
    name: Lint & Format Check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ConcernsCaseWork/ConcernsCaseWork.CypressTests

    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'ConcernsCaseWork/ConcernsCaseWork.CypressTests/package-lock.json'

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Check formatting and lint
        run: npm run format:check
